name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '57 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: true
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/wkProjects/docker-php-runtime
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{date 'YYYYMMDD-HHmmss'}}
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
